FineBlog/Controllers/BlogController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using FineBlog.Data;
using FineBlog.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FineBlog.Controllers
{
    public class BlogController : Controller
    {
        private readonly ApplicationDbContext _context;
        public INotyfService _notification { get; }

        public BlogController(ApplicationDbContext context, INotyfService notification)
        {
            _context = context;
            _notification = notification;
        }

        [HttpGet("[controller]/{slug}")]
        public IActionResult Post(string slug)
        {
            if (slug == "")
            {
                _notification.Error("Post not found");
                return View();
            }
            var post = _context.Posts!.Include(x=> x.ApplicationUser).FirstOrDefault(x=>x.Slug == slug);
            if (post == null)
            {
                _notification.Error("Post not found");
                return View();
            }
            var vm = new BlogPostVM()
            {
                Id = post.Id,
                Title = post.Title,
                AuthorName = post.ApplicationUser!.FirstName + " " + post.ApplicationUser.LastName,
                CreatedDate = post.CreatedDate,
                ThumbnailUrl = post.ThumbnailUrl,
                Description = post.Description,
                ShortDescription = post.ShortDescription,
            };
            return View(vm);
        }
    }
}

FineBlog/Controllers/HomeController.cs
using FineBlog.Data;
using FineBlog.Models;
using FineBlog.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using X.PagedList;

namespace FineBlog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, 
                                ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public  async Task<IActionResult> Index(int? page)
        {
            var vm = new HomeVM();
            var setting = _context.Settings!.ToList();
            vm.Title = setting[0].Title;
            vm.ShortDescription = setting[0].ShortDescription;
            vm.ThumbnailUrl = setting[0].ThumbnailUrl;
            int pageSize = 4; // limit item per page
            int pageNumber = (page ?? 1);
            vm.Posts = await _context.Posts!.Include(x => x.ApplicationUser).OrderByDescending(x=>x.CreatedDate).ToPagedListAsync(pageNumber, pageSize);
            return View(vm);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FineBlog/Views/Home/Index.cshtml
@model FineBlog.ViewModels.HomeVM
@using X.PagedList
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common

@{
    ViewData["Title"] = "Home Page";
    string thumbnailUrl = "";
    if(Model.ThumbnailUrl == "")
    {
        thumbnailUrl = "/blog/assets/img/home-bg.jpg";
    }
    else
    {
        thumbnailUrl = "/thumbnails/" + Model.ThumbnailUrl;
    }
}


<!-- Page Header-->
<header class="masthead" style="background-image: url('@thumbnailUrl')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>@Model.Title</h1>
                    <span class="subheading">@Model.ShortDescription</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            @foreach(var post in Model.Posts!)
            {
                <!-- Post preview-->
                <div class="post-preview">
                    <a asp-controller="Blog" asp-action="Post" asp-route-slug="@post.Slug">
                        <h2 class="post-title">@post.Title</h2>
                        <h3 class="post-subtitle">@post.ShortDescription</h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#!">@post.ApplicationUser!.FirstName @post.ApplicationUser!.LastName</a>
                        on @post.CreatedDate.ToShortDateString()
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            }

            Page @(Model?.Posts.PageCount < Model?.Posts.PageNumber ? 0 : Model?.Posts.PageNumber) of @Model?.Posts.PageCount
            @Html.PagedListPager(Model?.Posts,page => Url.Action("Index",
            new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
            new PagedListRenderOptions()
            {
            ContainerDivClasses = new List<string> {"d-flex justify-content-start mb-4"},
            UlElementClasses = new List<string> {"pagination"},
            LiElementClasses = new List<string> {"btn btn-primary mx-1 text-uppercase"},
            ActiveLiElementClass =  "active",
            })
        </div>
    </div>
</div>